GOOGLE_API_KEY = "AIzaSyC5CbNBWuNQsUkjDTE1Gey-QDiyMKgzuqk"

[connections.gsheets]
type = "service_account"
project_id = "conselho-classe"
private_key_id = "3cbef1370ebd4d7631c8753a39fbc3e3d126d422"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyUpZEnf3AbUO4
LhZzDw9B9tl79DRg9HTHGk4A6mGvPWZ1FPlGkrVbGb1icg5UcyEst/fwgCz2l6/P
CFRvUFYVMu37FEdHWHvUsdgjEQFICVATcR8oFv8nmHFkHzNxHoXEqfgUITnlSZf4
FTYjbcGYpbJcLAnZNAmH2sZYfRQieZ8vRffd7fJ8RWGS6LOFCgE0ycsUoToNZS/O
sDnms0t0Ik9rOo6v6uDXpZIijYOyGbJETymyO8N7fDmPPr1aGCCAoh4aadOYcthi
LXnlPDSj0vgawkAQEnHqCzMjmU48B4ViyeTO5SkBCx12V42K2YSftywHinMQtbTK
+1kCW6qhAgMBAAECggEAAPwGXPp9kLT1uFAGUxQqpJXGG3pkmeKtnJ4JP1Vr7MOP
M88l5Wkoz8gBiPgp2rbgQHLDT1hIz0N0/rTMQQlRsVgkstO4xUTAecMR1zc4QWde
Qh44MqCmX9fGS/wFXN7zFHvu/P72Nq0oZe/piqpn5MWo6Xv7ga/JK+8l9E37+Qj+
HbLzMqCl9Ex5y4/Qxu62mwKjvE35gYRjdLkKqelvJi8BhkIudEcjznvFnvmxomNj
y6qgF/5hoOvybVcDNzUsJPvPlsLnjCT1FzkI7GyVkziQV3ahN5whdqvdkPH77ItI
56vW/Mnae5nn8wjhBuun8m4/lv3LiF9XA+pqqnLHEQKBgQDmFb0Lkr2H3u3An3Bv
cmzALEwhPqSm3jRw4VeRm92nZvDTeTNRr9ubk2sabDUGhiIvIZVahRwfp/cesoha
G3OrK8LGfI59qBmhX4guiBeG/7yFuSeMLa4GekqJAbZo5zRZUCu9DFgAK7lcvgkG
L7iEtHG5Bn6+wc+KNMC8KQW+sQKBgQDGaFXrfLGeb5P4IT/dTXr0jFHMXk5uTyYm
0FaoxHaymwkYWQIAk+o9y1CMf5juUkpA+/R7/9BaKNCFixPVUFJmGOUg0aUqp8bw
kffXZiiz+EaxVXaqsYvblyR7ZCOj/u5cQulln7qPamzp2Av5uQPRjrWgHher4EIB
i4f8xesG8QKBgFmI9hLt3IFmGAEQSnGkBnvWAR4iwXIKIEAZALmx/NRq86ZnkLfm
BkCJYnFa0FukkOLkX7lk+Se8dibk9LiT3DQtCFOzHsP5SVgJ0/W/keA/3n3vKlub
XxA4QI8GMpSp/C4RS6P6jLgsS6qybNKSeWxyx5pn06SpyPiQRLwz/n9RAoGBAIQt
RfAXpgyysJUBMZaw41S/lk7cFMwQFo6NBO5x09GwzyJVSaww3kBEjmjLKIq8b5NT
RtDE33zw69nLiW72j65Mr3hpser00ue5lq788+jRYecJ1IBqv42O51L8p3G9h/YW
7X4yJwscD2rJ71ByHUUiGYWOBp8OS2rUFcgj4itBAoGBALQ5Ou7rvtYA7ydbNoWR
/pedhddhhLobms1LoJ0TzyAgDM6StHVVr2bFrQYGIYN+0EjToAwrr4wCc+9iLtbE
yLhCTMzJCsMmGIzZ7wpMi7CSkusjxHzwxTOuCg3WmaH3lw5OgFvEcwbf59s0lIz6
Px8ZC5bVG7Nfx43rZGH4JzLQ
-----END PRIVATE KEY-----"""
client_email = "conselho-bot@conselho-classe.iam.gserviceaccount.com"
client_id = "116941952147082691765"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/conselho-bot%40conselho-classe.iam.gserviceaccount.com"
universe_domain = "googleapis.com"